### ISSUE TITLE
Add github actions for CI ?

### ISSUE THREAD

**Issue by kwisatz** [tentwentyfour/nextcloud-link#11]
We could run CI on github using _actions_, but not with the current set-up that uses `docker-compose`.
At least I don't think there are _actions_ to support that.
Instead, all Nextcloud functionality should probably be mocked anyway.

```
name: Node.js CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true

```
